apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio  
  name: minio
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9001
        volumeMounts:
        - mountPath: /data
          name: localvolume 
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
      volumes:
      - name: localvolume
        hostPath: 
          path: /mnt/disk1/data 
          type: DirectoryOrCreate 