apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio  
  name: minio
  namespace: default 
spec:
  selector:
    matchLabels:
      app: minio
  template:
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_DOMAIN
          value: gravitate-health.lst.tfo.upm.es
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://gravitate-health.lst.tfo.upm.es/bucket/