apiVersion: batch/v1
kind: Job
metadata:
  name: configure-minio-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: configure-minio
        image: quay.io/minio/mc:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while ! mc alias set myminio http://minio-service:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
            echo "Waiting for MinIO to be ready..."
            sleep 5
          done
          mc mb --ignore-existing myminio/gh-bucket && \
          mc anonymous set download myminio/gh-bucket
          exit 0
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio.root.user
              optional: false
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio.root.password
              optional: false
      restartPolicy: Never
