apiVersion: apps/v1
kind: Deployment
metadata:
  name: supporting-material-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supporting-material-manager
  template:
    metadata:
      labels:
        app: supporting-material-manager
    spec:
      containers:
        - name: supporting-material-manager
          image: gravitate-registry.cr.de-fra.ionos.com/supporting-material-manager:v0.1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: supporting-material-manager
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio.root.user
                optional: false
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio.root.password
                optional: false
          resources: {}
          #  limits:
          #    cpu: "1"
          #    memory: "512Mi"
          #  requests:
          #    cpu: "0.5"
          #    memory: "256Mi"