apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smm-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - gh-gateway
  http:
    - match:
        - uri:
            prefix: /smm/
      #rewrite:
      #  uri: "/"
      route:
        - destination:
            host: smm-service.default.svc.cluster.local
            port:
              number: 3000