apiVersion: v1
kind: ConfigMap
metadata:
  name: smm-config
data:
  APP_PORT: "3000"
  MINIO_URL: ""
  MINIO_PORT: "9000"
  ACCESS_KEY: ""
  SECRET_KEY: ""
  FHIR_URL: "gravitate-health.lst.tfo.upm.es/ips/api/fhir/"
  GH_BUCKET: "gh-bucket"
  API_URL: "gravitate-health.lst.tfo.upm.es/smm"