apiVersion: apps/v1
kind: Deployment
metadata:
  name: smm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smm
  template:
    metadata:
      labels:
        app: smm
    spec:
      containers:
        - name: smm
          image: example:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: smm-config
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"